issues:
  'minimum open issues collaborator':
    do:
      assign:
        minimum:
          state: open
          type: issue
          team: Developers
  'minimum list':
    do:
      assign:
        minimum:
          - radontt
          - roman-dezhin
          - sibero
             
