issues:
  'label bug': 
    if: 
      action: opened
      title: bug
    then: 
      label: bug
  'assign gor if label bug':
    if:
      action: labeled
      label: bug
    then:
      assign: Gormartsen
  'assign support':
    do: 
      label: "New request"
