issues:
  'label bug': 
    if: 
      title: bug
      from: any
      user: Gormartsen
    then: 
      label: bug
  'assign support':
    do: 
      assignee: minimum_open()
      label: "New request"
